baseURL = "/"
languageCode = "en-gb"
title = "RelnoBlank"
paginate = 5
theme = "PaperMod"

enableEmoji = true

[analytics.google]
siteVerificationTag = "XYZabc"

[taxonomies]
   tag = "tags"
   category = "categories"
   author = "author"

[params.homeInfoParams]
Title = "SEO & PPC Blog"
Content = '''Learn & implement the right SEO and PPC tools for your creative business or career
- 

- We talk about news in the industry, on-page/off-page SEO, paid & organic marketing and how to get familiar with data & reporting.
-
- Blog Categories: [SEO](/blog/seo) | [PPC](/blog/marketing) | [Other Tools](/blog/others) | [About Me](/author/kami-faure)
- Latest posts below 👇 '''

[params.profileMode]
enabled = false
title = "<Title>"


[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

    [[languages.en.menu.main]]
    name = "About"
    url = "/author/kami-faure"
    weight = 5

    [[languages.en.menu.main]]
    name = "SEO"
    url = "/blog/seo/"
    weight = 6

[[languages.en.menu.main]]
    name = "PPC"
    url = "/blog/marketing/"
    weight = 10

    [[languages.en.menu.main]]
    name = "Other Tools"
    url = "/blog/others/"
    weight = 20


[params]
env = "production"
description = "SEO & PPC blog"
logo = "favicon-32x32.png"
copyright = "All rights reserved to RelnoBlank"
author = "Kami Faure"
ShowShareButtons = true
comments = true
ShowBreadCrumbs = true
TocOpen = true
ShowReadingTime = true
ShowPostNavLinks = true

[Author]
  name = "Kami Faure"

