baseURL = "/"
languageCode = "en-gb"
title = "noreltag"
paginate = 5
theme = "PaperMod"

enableEmoji = true
enableRobotsTXT = true


[analytics.google]
siteVerificationTag = "XYZabc"

[taxonomies]
   tag = "tags"
   category = "categories"
   author = "author"

[params.homeInfoParams]
Title = "SEO & PPC Blog"
Content = '''Learn & implement the right SEO and PPC strategies for your business or career
- 
- We talk about news in the industry, tech/on-page/off-page SEO, paid & organic marketing + how to interpret data & reporting.
-
- Blog Categories: [SEO](/blog/search-engine-optimisation/) | [PPC](/blog/marketing) | [Other Tools](/blog/others) | [Talks & News](/tags/talks-news/) | [About](/about/)
- Latest posts below 👇 '''

[params.profileMode]
enabled = false
title = "<Title>"


[minify]
disableXML = true

[languages.en]
languageName = "English"
weight = 1

    [[languages.en.menu.main]]
    name = "About"
    url = "/about/"
    weight = 5

    [[languages.en.menu.main]]
    name = "SEO"
    url = "/blog/search-engine-optimisation/"
    weight = 6

[[languages.en.menu.main]]
    name = "PPC"
    url = "/blog/marketing/"
    weight = 10

    [[languages.en.menu.main]]
    name = "Other Tools"
    url = "/blog/others/"
    weight = 20


[params]
# env = "production"
description = "noreltag is an SEO & PPC blog"
logo = "favicon-32x32.png"
copyright = "All rights reserved to noreltag"
author = "Kami Faure"
ShowShareButtons = true
comments = true
ShowBreadCrumbs = true
TocOpen = true
ShowReadingTime = true
ShowPostNavLinks = true

[Author]
  name = "Kami Faure"

